language: node_js
node_js:
  - '6'
install: npm install && bower install
env:
notifications:
  slack:
    secure: XDS9fqgiWUYA3bnV3RtRK+vIRoZ8HC3BHSD3pBxdAdZnezjzPirliUttDiEMEXiUjZp8SNxnA1r/4LnPYMaubQKBdhzbfUnD7P5pgFqvTTCebpco1xUf7HgeCVjwWYmxtXWxIWYqzSpaLIgBQW9WnNBWs/QPq66D70y1xCqijS9cV8tOXn0sHeXX+nHyAJTw2ZiQznzEKCmGiJaMghEdUn24VDbqjR4mw7gylyAovqyoZyTu+YORSbBdo4Ks+G2mwtQb1DqFtT8Av9AXylIT+K6zinkNXtoehpKsEzbewD7cSrXnDRBi7sadirjqw0GPj+NGpZqePV69eBbcaqETy2T3I1ikf3U8cD9c9eWPweFtLcuEHPQEdHwC5cDvVBVg2WE+08PyA+P34O3AjlrDULRRKMj12Ltc9hwihUm99r+lAhyKNkSSqMJ+sLY/JzqaTIC/8J9IZOQq/GGQDgT2ZNxparO5G9ee3of9utdsL1rzjwEo3n+dyJ3sOQfRAsK3sjTS47OwFHCFLsayzMMh/uM0qhk43tbCrZCfm5klDcauySCHbZpwbJMamsFrd2raWV3d9cmGFhUoXc0puxhdtWjmJhLYvc3wDEc1ebZPm/2f9MihmilLG0kUVpKFKGIfgmcXb/z9eTuj1mdq7RaaBTF+a90U9cNJu2zdnr9kDFU=
